# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('ip', models.CharField(max_length=15)),
                ('method', models.CharField(max_length=6)),
                ('url', models.CharField(max_length=1000)),
                ('referer', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('querystring', models.TextField(blank=True, default=None, null=True)),
                ('status', models.IntegerField()),
                ('reason', models.CharField(max_length=64)),
            ],
        ),
    ]
