# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitstat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
